## Reproducible Research: Peer Assessment 2

# Analysis of Health and Economic Impacts of Severe Weather Events Across the United States

By Sagi Greenstine (sagigr@gmail.com)
Date: 26-10-2015

## Assignment

The basic goal of this assignment is to explore the NOAA Storm Database and answer some basic questions about severe weather events. You must use the database to answer the questions below and show the code for your entire analysis. Your analysis can consist of tables, figures, or other summaries. You may use any R package you want to support your analysis.

## Synopsis

This analysis based on the U.S. National Oceanic and Atmospheric Administration's (NOAA) Storm Database, that contains the events starting from 1950 until November 2011. 
The NOAA Storm Database tracks characteristics of major storms and weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.
This data analysis project tries to answer the following questions:
1. Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?
2. Across the United States, which types of events have the greatest economic consequences?

The conclusion of this analysis is...



## Data Processing

### Loading and preprocessing the data

```{r loaddata}
if(!exists("stormdata")){
  stormdata <- read.csv("./repdata-data-StormData.csv.bz2", row.names = NULL, nrows=902297, check.names=F,           stringsAsFactors=F, header=T, sep=',', na.strings="NA", comment.char="", quote='\"')
}
```



## Results

#### 1. Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?




#### 2. Across the United States, which types of events have the greatest economic consequences?

